/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface ArbitrumNFTCoreInterface extends ethers.utils.Interface {
  functions: {
    'adminMint(address,uint256)': FunctionFragment
    'claimNFT(bytes32[])': FunctionFragment
    'claimed(address)': FunctionFragment
    'claimedCounter()': FunctionFragment
    'debtValueThreshold()': FunctionFragment
    'ga()': FunctionFragment
    'gm()': FunctionFragment
    'gn()': FunctionFragment
    'initialize(address,address,address,address,address,address,address,address,address,address,address)': FunctionFragment
    'levValueThreshold()': FunctionFragment
    'mintGA(bytes32[])': FunctionFragment
    'mintGM(bytes32[])': FunctionFragment
    'mintGN(bytes32[])': FunctionFragment
    'owner()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setDebtValueThreshold(uint256)': FunctionFragment
    'setLevValueThreshold(uint256)': FunctionFragment
    'setXu3lpBalanceThreshold(uint256)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'wagmi()': FunctionFragment
    'xu3lpBalanceThreshold()': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'adminMint',
    values: [string, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'claimNFT',
    values: [BytesLike[]]
  ): string
  encodeFunctionData(functionFragment: 'claimed', values: [string]): string
  encodeFunctionData(
    functionFragment: 'claimedCounter',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'debtValueThreshold',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'ga', values?: undefined): string
  encodeFunctionData(functionFragment: 'gm', values?: undefined): string
  encodeFunctionData(functionFragment: 'gn', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'levValueThreshold',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'mintGA', values: [BytesLike[]]): string
  encodeFunctionData(functionFragment: 'mintGM', values: [BytesLike[]]): string
  encodeFunctionData(functionFragment: 'mintGN', values: [BytesLike[]]): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'setDebtValueThreshold',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'setLevValueThreshold',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'setXu3lpBalanceThreshold',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string]
  ): string
  encodeFunctionData(functionFragment: 'wagmi', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'xu3lpBalanceThreshold',
    values?: undefined
  ): string

  decodeFunctionResult(functionFragment: 'adminMint', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimNFT', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'claimedCounter',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'debtValueThreshold',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'ga', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'gm', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'gn', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'levValueThreshold',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'mintGA', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'mintGM', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'mintGN', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setDebtValueThreshold',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setLevValueThreshold',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setXu3lpBalanceThreshold',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'wagmi', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'xu3lpBalanceThreshold',
    data: BytesLike
  ): Result

  events: {
    'OwnershipTransferred(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export class ArbitrumNFTCore extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ArbitrumNFTCoreInterface

  functions: {
    adminMint(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'adminMint(address,uint256)'(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    claimNFT(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'claimNFT(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    claimed(arg0: string, overrides?: CallOverrides): Promise<[boolean]>

    'claimed(address)'(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    claimedCounter(overrides?: CallOverrides): Promise<[BigNumber]>

    'claimedCounter()'(overrides?: CallOverrides): Promise<[BigNumber]>

    debtValueThreshold(overrides?: CallOverrides): Promise<[BigNumber]>

    'debtValueThreshold()'(overrides?: CallOverrides): Promise<[BigNumber]>

    ga(overrides?: CallOverrides): Promise<[string]>

    'ga()'(overrides?: CallOverrides): Promise<[string]>

    gm(overrides?: CallOverrides): Promise<[string]>

    'gm()'(overrides?: CallOverrides): Promise<[string]>

    gn(overrides?: CallOverrides): Promise<[string]>

    'gn()'(overrides?: CallOverrides): Promise<[string]>

    initialize(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'initialize(address,address,address,address,address,address,address,address,address,address,address)'(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    levValueThreshold(overrides?: CallOverrides): Promise<[BigNumber]>

    'levValueThreshold()'(overrides?: CallOverrides): Promise<[BigNumber]>

    mintGA(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'mintGA(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    mintGM(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'mintGM(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    mintGN(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'mintGN(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    'owner()'(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

    'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

    setDebtValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'setDebtValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    setLevValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'setLevValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    setXu3lpBalanceThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'setXu3lpBalanceThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    wagmi(overrides?: CallOverrides): Promise<[string]>

    'wagmi()'(overrides?: CallOverrides): Promise<[string]>

    xu3lpBalanceThreshold(overrides?: CallOverrides): Promise<[BigNumber]>

    'xu3lpBalanceThreshold()'(overrides?: CallOverrides): Promise<[BigNumber]>
  }

  adminMint(
    nft: string,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'adminMint(address,uint256)'(
    nft: string,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  claimNFT(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'claimNFT(bytes32[])'(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  claimed(arg0: string, overrides?: CallOverrides): Promise<boolean>

  'claimed(address)'(arg0: string, overrides?: CallOverrides): Promise<boolean>

  claimedCounter(overrides?: CallOverrides): Promise<BigNumber>

  'claimedCounter()'(overrides?: CallOverrides): Promise<BigNumber>

  debtValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

  'debtValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

  ga(overrides?: CallOverrides): Promise<string>

  'ga()'(overrides?: CallOverrides): Promise<string>

  gm(overrides?: CallOverrides): Promise<string>

  'gm()'(overrides?: CallOverrides): Promise<string>

  gn(overrides?: CallOverrides): Promise<string>

  'gn()'(overrides?: CallOverrides): Promise<string>

  initialize(
    _gm: string,
    _ga: string,
    _gn: string,
    _wagmi: string,
    _xu3lpa: string,
    _xu3lpb: string,
    _liquidityPool: string,
    _xassetLev0: string,
    _xassetLev1: string,
    _xassetLev2: string,
    _whitelistedAddresses: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'initialize(address,address,address,address,address,address,address,address,address,address,address)'(
    _gm: string,
    _ga: string,
    _gn: string,
    _wagmi: string,
    _xu3lpa: string,
    _xu3lpb: string,
    _liquidityPool: string,
    _xassetLev0: string,
    _xassetLev1: string,
    _xassetLev2: string,
    _whitelistedAddresses: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  levValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

  'levValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

  mintGA(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'mintGA(bytes32[])'(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  mintGM(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'mintGM(bytes32[])'(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  mintGN(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'mintGN(bytes32[])'(
    merkleProof: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  'owner()'(overrides?: CallOverrides): Promise<string>

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

  'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

  setDebtValueThreshold(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'setDebtValueThreshold(uint256)'(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  setLevValueThreshold(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'setLevValueThreshold(uint256)'(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  setXu3lpBalanceThreshold(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'setXu3lpBalanceThreshold(uint256)'(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'transferOwnership(address)'(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  wagmi(overrides?: CallOverrides): Promise<string>

  'wagmi()'(overrides?: CallOverrides): Promise<string>

  xu3lpBalanceThreshold(overrides?: CallOverrides): Promise<BigNumber>

  'xu3lpBalanceThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    adminMint(
      nft: string,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    'adminMint(address,uint256)'(
      nft: string,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    claimNFT(merkleProof: BytesLike[], overrides?: CallOverrides): Promise<void>

    'claimNFT(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>

    claimed(arg0: string, overrides?: CallOverrides): Promise<boolean>

    'claimed(address)'(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    claimedCounter(overrides?: CallOverrides): Promise<BigNumber>

    'claimedCounter()'(overrides?: CallOverrides): Promise<BigNumber>

    debtValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'debtValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

    ga(overrides?: CallOverrides): Promise<string>

    'ga()'(overrides?: CallOverrides): Promise<string>

    gm(overrides?: CallOverrides): Promise<string>

    'gm()'(overrides?: CallOverrides): Promise<string>

    gn(overrides?: CallOverrides): Promise<string>

    'gn()'(overrides?: CallOverrides): Promise<string>

    initialize(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: CallOverrides
    ): Promise<void>

    'initialize(address,address,address,address,address,address,address,address,address,address,address)'(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: CallOverrides
    ): Promise<void>

    levValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'levValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

    mintGA(merkleProof: BytesLike[], overrides?: CallOverrides): Promise<void>

    'mintGA(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>

    mintGM(merkleProof: BytesLike[], overrides?: CallOverrides): Promise<void>

    'mintGM(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>

    mintGN(merkleProof: BytesLike[], overrides?: CallOverrides): Promise<void>

    'mintGN(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>

    owner(overrides?: CallOverrides): Promise<string>

    'owner()'(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>

    setDebtValueThreshold(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    'setDebtValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    setLevValueThreshold(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    'setLevValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    setXu3lpBalanceThreshold(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    'setXu3lpBalanceThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>

    wagmi(overrides?: CallOverrides): Promise<string>

    'wagmi()'(overrides?: CallOverrides): Promise<string>

    xu3lpBalanceThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'xu3lpBalanceThreshold()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter
  }

  estimateGas: {
    adminMint(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    'adminMint(address,uint256)'(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    claimNFT(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    'claimNFT(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    claimed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    'claimed(address)'(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    claimedCounter(overrides?: CallOverrides): Promise<BigNumber>

    'claimedCounter()'(overrides?: CallOverrides): Promise<BigNumber>

    debtValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'debtValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

    ga(overrides?: CallOverrides): Promise<BigNumber>

    'ga()'(overrides?: CallOverrides): Promise<BigNumber>

    gm(overrides?: CallOverrides): Promise<BigNumber>

    'gm()'(overrides?: CallOverrides): Promise<BigNumber>

    gn(overrides?: CallOverrides): Promise<BigNumber>

    'gn()'(overrides?: CallOverrides): Promise<BigNumber>

    initialize(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'initialize(address,address,address,address,address,address,address,address,address,address,address)'(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    levValueThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'levValueThreshold()'(overrides?: CallOverrides): Promise<BigNumber>

    mintGA(merkleProof: BytesLike[], overrides?: Overrides): Promise<BigNumber>

    'mintGA(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    mintGM(merkleProof: BytesLike[], overrides?: Overrides): Promise<BigNumber>

    'mintGM(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    mintGN(merkleProof: BytesLike[], overrides?: Overrides): Promise<BigNumber>

    'mintGN(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>

    'renounceOwnership()'(overrides?: Overrides): Promise<BigNumber>

    setDebtValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    'setDebtValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    setLevValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    'setLevValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    setXu3lpBalanceThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    'setXu3lpBalanceThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    wagmi(overrides?: CallOverrides): Promise<BigNumber>

    'wagmi()'(overrides?: CallOverrides): Promise<BigNumber>

    xu3lpBalanceThreshold(overrides?: CallOverrides): Promise<BigNumber>

    'xu3lpBalanceThreshold()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    adminMint(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'adminMint(address,uint256)'(
      nft: string,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    claimNFT(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'claimNFT(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    claimed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'claimed(address)'(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    claimedCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'claimedCounter()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    debtValueThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'debtValueThreshold()'(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    ga(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'ga()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    gm(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'gm()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    gn(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'gn()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    initialize(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'initialize(address,address,address,address,address,address,address,address,address,address,address)'(
      _gm: string,
      _ga: string,
      _gn: string,
      _wagmi: string,
      _xu3lpa: string,
      _xu3lpb: string,
      _liquidityPool: string,
      _xassetLev0: string,
      _xassetLev1: string,
      _xassetLev2: string,
      _whitelistedAddresses: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    levValueThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'levValueThreshold()'(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    mintGA(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'mintGA(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    mintGM(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'mintGM(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    mintGN(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'mintGN(bytes32[])'(
      merkleProof: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>

    'renounceOwnership()'(overrides?: Overrides): Promise<PopulatedTransaction>

    setDebtValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'setDebtValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    setLevValueThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'setLevValueThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    setXu3lpBalanceThreshold(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'setXu3lpBalanceThreshold(uint256)'(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    wagmi(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'wagmi()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    xu3lpBalanceThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'xu3lpBalanceThreshold()'(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>
  }
}
