name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js 10.23.1
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.1'

      - name: Install dependencies
        run: yarn
        
      - name: Run tests
        run: yarn test
